@startuml
!include <C4/C4_Container>
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam backgroundColor transparent

Boundary(b0, "", "") {
    System_Ext(app0, "Application", "Application that wants to send or receive large files")
    SystemDb_Ext(file0, "File Share\n[Optional]", "Holds Files")
    System(fs, "File Server", "Receives files through TUS Protocol and exposes files through HTTP GET Protocol")
}
Boundary(b1, "", "") {
    System(fc, "File Client", "Uploads files through the TUS protocol and downloads files through HTTP GET Protocol")
    System_Ext(app1, "Application", "Application that wants to send or receive large files")
    SystemDb_Ext(file1, "File Share\n[Optional]", "Holds Files")
}

Rel_R(app0, fs, "Uploads File(UploadRequest)s and downloads File(DownloadRequest)s", "REST|SOAP/HTTPS")
Rel(app0, file0, "Stores and Retrieves Files", "File")
Rel(fs, file0, "Stores and Retrieves Files", "File")
Rel_L(fc, fs, "Uploads and Downloads Files", "TUS&HTTPGET/HTTPS ")
Rel_L(app1, fc, "Uploads File(UploadRequest)s and downloads File(DownloadRequest)s", "REST|SOAP/HTTPS")
Rel(app1, file1, "Stores and Retrieves Files", "File")
Rel(fc, file1, "Stores and Retrieves Files", "File")

SHOW_DYNAMIC_LEGEND()

@enduml