@startuml
!theme reddress-lightorange

skinparam backgroundColor transparent
' skinparam responseMessageBelowArrow true

title Exchange Files

participant "Custom Application" as app
participant "File Server" as fs
participant "File Client" as fc

... <b>Download File ...

autonumber 1.1
app -> fs: FileService.uploadFile(userId, newFile)
activate fs

fs --> app: <path>
deactivate fs

fc -> fs: HTTP download file
activate fs

fs --> fc: <file>
deactivate fs

... <b>Upload File ...

autonumber 2.1
fc -> fs: tus upload file
activate fs

fs --> fc
deactivate fs

app -> fs: FileService.downloadFile(path)
activate fs

fs --> app: <File>
deactivate fs

...
@enduml