@startuml
!theme reddress-lightorange

skinparam backgroundColor transparent
' skinparam responseMessageBelowArrow true

' title File Download

participant "Custom Application" as app
participant "File Server" as fs
participant "File Client" as fc

autonumber 1

fc -> fs: upload file
activate fs

fs --> fc
deactivate fs

app -> fs: download file
activate fs

fs --> app
deactivate fs

@enduml