@startuml
!theme reddress-lightorange

skinparam backgroundColor transparent
' skinparam responseMessageBelowArrow true

' title File Download

participant "Custom Application" as app
participant "File Server" as fs
participant "File Client" as fc

fc -> fs: **1.** tus upload file
activate fs

fs --> fc
deactivate fs

app -> fs: **2.** downloadFile(path)
activate fs

fs --> app: <file>
deactivate fs

@enduml